### ISSUE TITLE
ImportError: cannot import name ProgressionDialog

### ISSUE THREAD

**Issue by nvictor** [bspaans/improviser#1]
hello, i can't run qtImproviser =[

this is what i get:

  C:\improviser-0.8.6.2.1\improviser>c:\epython25\python.exe qtImproviser.py
  Traceback (most recent call last):
    File "qtImproviser.py", line 4, in <module>
      from qtGUI.MainWindow import ImproviserMainWindow
    File "C:\improviser-0.8.6.2.1\improviser\qtGUI\MainWindow.py", line 4, in <module>
      from ProgressionDialog import ProgressionDialog
  ImportError: cannot import name ProgressionDialog

**Comment by bspaans** [comment]
Last time I checked the windows version was broken because of a silly file system issue (there isn't a distinction between upper and lowercase filenames on Windows). As soon as I have some time to work on this program I will change this.

**Comment by bspaans** [comment]
As of version 0.8.6.3 this issue has been resolved. I got a working program running in a WinXP VM. Thanks for reporting.
